version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "on-failure"

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express
    expose:
      - "3500"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    restart: "on-failure"
